# Generated by Django 3.2.6 on 2021-10-16 06:05

import datetime
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='house/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image_2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='house/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image_3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='house/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image_4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='house/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='feature_image',
            field=models.ImageField(upload_to='house/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
