# Generated by Django 3.2.6 on 2021-10-16 06:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20211016_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 6, 15, 3, 560218, tzinfo=utc)),
        ),
    ]
