# Generated by Django 3.2.6 on 2021-10-24 05:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 5, 19, 5, 101073, tzinfo=utc)),
        ),
    ]
